---
services:
  jaeger:
    image: jaegertracing/all-in-one:1.60
    container_name: otel-jaeger
    ports:
      - 16686:16686
      - 4317 # OTLP gRPC receiver
      - 4318 # OTLP http receiver
      - 14268
      - 14250
    environment:
      - TZ=Asia/Shanghai
      - OTEL_TRACES_SAMPLER=always_off
      - LOG_LEVEL=info
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './ui.json:/ui.json'
    command:
      -  --query.ui-config=/ui.json
