
# This is a complete configuration to deploy Loki backed by the filesystem.
# The index will be shipped to the storage via tsdb-shipper.

auth_enabled: false

server:
  http_listen_port: 3100

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki

schema_config:
  configs:
  - from: 2024-09-20
    store: tsdb
    object_store: filesystem
    schema: v13
    index:
      prefix: index_
      period: 24h

storage_config:
  filesystem:
    directory: /tmp/loki/chunks


# 摄入限制配置
limits_config:
  ingestion_rate_mb: 1024  # 每个用户每秒的采样率限制（单位：MB）
  ingestion_burst_size_mb: 1024  # 每个用户允许的采样突发大小（单位：MB）
  max_streams_per_user: 10000  # 每个用户的最大日志流个数
  max_entries_limit_per_query: 5000  # 查询返回条目的限制

query_range:
    # make queries more cache-able by aligning them with their step intervals
    align_queries_with_step: true
    max_retries: 5
    cache_results: true

    results_cache:
      cache:
        # We're going to use the embedded cache
        embedded_cache:
          enabled: true
          max_size_mb: 100
          ttl: 24h

  limits_config:
    max_cache_freshness_per_query: '10m'
    # parallelize queries in 15min intervals
    split_queries_by_interval: 15m

  frontend:
    log_queries_longer_than: 5s
    downstream_url: http://localhost:3100
    compress_responses: true
