---
include:
  - a.yml
  - b.yml

services:
  hotrod:
    image: example-hotrod:1.60
    container_name: sw-hotrod
    logging:
      options:
        max-size: 50m
        max-file: "3"
    command: [ "all" ]
    ports:
      - 8080:8080
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel:4318
    depends_on:
      - otel
    networks:
      - sw



 ##Locust 是一个易于使用的开源负载测试工具
  load-hotrod:
    image: locustio/locust:2.31.5
    container_name: sw-load-hotrod
    environment:
      TZ: Asia/Shanghai
      ATTACKED_HOST: https://sw-ui.local.org
      LOCUST_MODE: standalone
      NO_PROXY: standalone
      TASK_DELAY_FROM: 5
      TASK_DELAY_TO: 30
      QUIET_MODE: "${QUIET_MODE:-false}"
      LOCUST_OPTS: "--headless -u 10 -r 1"
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - /opt/test/locust_script:/home/locust
      - /opt/test/ca/local.org.crt:/etc/ssl/certs/local.org.crt
    ports:
      - 18089:8089
    networks:
      - s