---
version: '3.8'
services:
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.15.0
 #   image: docker.elastic.co/beats/metricbeat:7.17.1
    container_name: metricbeat
    volumes:
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - ./modules.d:/usr/share/metricbeat/modules.d
      - /opt/monitor/elasticsearch_exporter-1.7.0/ssl:/opt:ro
    ports:
      - 9201:9201
    extra_hosts:
       - "es.local.org:192.168.122.1" # 添加主机名
    command: metricbeat -e -c /usr/share/metricbeat/metricbeat.yml 

  # url  http://local.org:9201/

