global:
  scrape_interval: 8s     # By default, scrape targets every 15 seconds.
  scrape_timeout: 8s
  evaluation_interval: 5m
  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #   stack: "apisix"

remote_write:
  - url: "http://local.org:18080/remote_write_prometheusbeat"
 # - url: "http://local.org:9201/remote_write"
    # write_relabel_configs:
    #   - source_labels: [job]
    #     regex: 'prometheus'
    #     action: keep
    remote_timeout: 30s


scrape_configs:
    # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
   - job_name: "prometheus"
     scrape_interval: 5s
     static_configs:
        - targets: ["localhost:9090"]
    # - job_name: "apisix"
    #   scrape_interval: 5s
    #   metrics_path: "/apisix/prometheus/metrics"
    #   static_configs:
    #     - targets: ["apisix:9091"]
   - job_name: 'nginx-monitoring'
     scrape_interval: 10s
     metrics_path: "/metrics"
     static_configs:
        - targets: ['local.org:9145']
          labels:
             service: nginx-service
             service_instance_id: e2e-test-instance
   - job_name: 'elasticsearch-monitoring'
     scrape_interval: 10s
     static_configs:
       - targets: ['local.org:9114']
   - job_name: "vm-monitoring" # make sure to use this in the vm.yaml to filter only VM metrics
     scrape_interval: 10s
     static_configs:
        - targets: ["local.org:9100"]
   - job_name: 'mysql-monitoring'
     scrape_interval: 5s
     static_configs:
       - targets: ['local.org:9104']
         labels:
           host_name: local.org:3305
   - job_name: "postgresql-monitoring"
     scrape_interval: 5s
     static_configs: #["postgres-exporter:9187","postgres-exporter_2:9187","postgres-exporter_3:9187"]
        - targets: ["local.org:9187"]
          labels:
            host_name: local.org:5433
   - job_name: 'redis-monitoring'
     scrape_interval: 5s
     static_configs:
       - targets: ['local.org:9121']
         labels:
           host_name: local.org:9121
