global:
  scrape_interval: 8s     # By default, scrape targets every 15 seconds.
  scrape_timeout: 8s
  evaluation_interval: 5m
  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #   stack: "apisix"

#remote_write:
#  - url: "http://local.org:18080/remote_write_prometheusbeat"
#    remote_timeout: 30s


scrape_configs:
    # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
   - job_name: "prometheus"
     scrape_interval: 5s
     static_configs:
        - targets: ["localhost:9090"]
